// signalTracker.js -- Stratum v7.5
// -----------------------------------------------------------------
// Signal Performance Journal.  Tracks every signal generated by the
// system, every fill, every exit, and calculates running stats.
// This is the PROOF that sells a signal subscription service.
//
// "Our A+ graded signals have X% win rate with Y% average return"
//
// Persists to STATE_DIR/signal_journal.json (survives deploys).
// API: GET /api/signals/stats    → running performance stats
//      GET /api/signals/history  → full signal history
//      POST /api/signals/close   → manually close a signal
// -----------------------------------------------------------------

var fs = require('fs');
var path = require('path');

var STATE_DIR = process.env.STATE_DIR || '/tmp';
var JOURNAL_FILE = path.join(STATE_DIR, 'signal_journal.json');

// In-memory journal
var _signals = [];
var _loaded = false;

// -----------------------------------------------------------------
// PERSISTENCE
// -----------------------------------------------------------------
function load() {
  if (_loaded) return;
  try {
    var raw = fs.readFileSync(JOURNAL_FILE, 'utf8');
    _signals = JSON.parse(raw);
    if (!Array.isArray(_signals)) _signals = [];
    console.log('[SIGNAL-TRACKER] Loaded ' + _signals.length + ' signals from disk');
  } catch (e) {
    _signals = [];
  }
  _loaded = true;
}

function save() {
  try {
    fs.writeFileSync(JOURNAL_FILE, JSON.stringify(_signals, null, 2));
  } catch (e) {
    console.error('[SIGNAL-TRACKER] Save error:', e.message);
  }
}

// -----------------------------------------------------------------
// LOG A NEW SIGNAL (called when a trade is queued)
// -----------------------------------------------------------------
function logSignal(data) {
  load();
  var signal = {
    id: 'SIG_' + Date.now() + '_' + Math.random().toString(36).slice(2, 6),
    timestamp: new Date().toISOString(),
    date: new Date().toISOString().slice(0, 10),
    ticker: (data.ticker || '').toUpperCase(),
    direction: (data.direction || 'CALLS').toUpperCase(),
    grade: data.grade || null,
    source: data.source || 'UNKNOWN',
    triggerPrice: parseFloat(data.triggerPrice) || 0,
    // GEX at signal time
    gexPin: data.gexPin || null,
    gexFlip: data.gexFlip || null,
    gexRegime: data.gexRegime || null,
    // Fill data (populated on fill)
    filled: false,
    fillTime: null,
    entryPrice: null,  // option entry price
    contracts: data.contracts || 0,
    strike: data.strike || null,
    expiration: data.expiration || null,
    stopPrice: null,
    // Exit data (populated on close)
    closed: false,
    closeTime: null,
    exitPrice: null,
    exitReason: null,  // STOP, TARGET, MANUAL, EXPIRED
    // P&L (calculated on close)
    pnlDollar: null,
    pnlPercent: null,
    holdTimeMin: null,
    won: null,
  };

  _signals.push(signal);
  save();
  console.log('[SIGNAL-TRACKER] Logged: ' + signal.ticker + ' ' + signal.direction +
    ' | grade=' + signal.grade + ' | source=' + signal.source);
  return signal;
}

// -----------------------------------------------------------------
// LOG A FILL (called when order executes)
// -----------------------------------------------------------------
function logFill(signalId, fillData) {
  load();
  var sig = findSignal(signalId);
  if (!sig) {
    // Try to find by ticker + direction if no signalId
    if (fillData && fillData.ticker) {
      sig = findPendingByTicker(fillData.ticker, fillData.direction);
    }
  }
  if (!sig) {
    console.log('[SIGNAL-TRACKER] No pending signal found for fill');
    return null;
  }

  sig.filled = true;
  sig.fillTime = new Date().toISOString();
  sig.entryPrice = parseFloat(fillData.entryPrice) || 0;
  sig.contracts = fillData.contracts || sig.contracts;
  sig.stopPrice = parseFloat(fillData.stopPrice) || null;
  sig.gexPin = fillData.gexPin || sig.gexPin;
  sig.gexFlip = fillData.gexFlip || sig.gexFlip;
  sig.gexRegime = fillData.gexRegime || sig.gexRegime;

  save();
  console.log('[SIGNAL-TRACKER] Fill logged: ' + sig.ticker + ' @ $' + sig.entryPrice);
  return sig;
}

// -----------------------------------------------------------------
// LOG A CLOSE (called when position is exited)
// -----------------------------------------------------------------
function logClose(signalId, closeData) {
  load();
  var sig = findSignal(signalId);
  if (!sig) {
    if (closeData && closeData.ticker) {
      sig = findFilledByTicker(closeData.ticker, closeData.direction);
    }
  }
  if (!sig) return null;

  sig.closed = true;
  sig.closeTime = new Date().toISOString();
  sig.exitPrice = parseFloat(closeData.exitPrice) || 0;
  sig.exitReason = closeData.exitReason || 'MANUAL';

  // Calculate P&L
  if (sig.entryPrice && sig.exitPrice) {
    sig.pnlDollar = (sig.exitPrice - sig.entryPrice) * (sig.contracts || 1) * 100;
    sig.pnlPercent = ((sig.exitPrice - sig.entryPrice) / sig.entryPrice) * 100;
    sig.won = sig.pnlDollar > 0;
  }

  // Hold time
  if (sig.fillTime) {
    sig.holdTimeMin = Math.round((new Date(sig.closeTime) - new Date(sig.fillTime)) / 60000);
  }

  save();
  console.log('[SIGNAL-TRACKER] Close logged: ' + sig.ticker +
    ' | P&L: ' + (sig.pnlDollar >= 0 ? '+' : '') + '$' + (sig.pnlDollar || 0).toFixed(0) +
    ' (' + (sig.pnlPercent || 0).toFixed(1) + '%)');
  return sig;
}

// -----------------------------------------------------------------
// AUTO-CLOSE: scan TradeStation for closed positions and match
// -----------------------------------------------------------------
async function autoReconcile() {
  load();
  try {
    var ts = require('./tradestation');
    var token = await ts.getAccessToken();
    if (!token) return { error: 'no token' };

    var ACCOUNT = '11975462';
    var fetch2 = require('node-fetch');
    var today = new Date().toISOString().slice(0, 10);

    // Get today's closed orders
    var ordRes = await fetch2('https://api.tradestation.com/v3/brokerage/accounts/' + ACCOUNT +
      '/historicalorders?since=' + today, {
      headers: { 'Authorization': 'Bearer ' + token },
    });
    if (!ordRes.ok) return { error: 'order fetch failed' };
    var ordData = await ordRes.json();
    var orders = ordData.Orders || [];

    var closedCount = 0;
    // Find SELLTOCLOSE fills
    for (var i = 0; i < orders.length; i++) {
      var ord = orders[i];
      if (ord.Status !== 'FLL' && ord.Status !== 'Filled') continue;

      var legs = ord.Legs || [];
      for (var j = 0; j < legs.length; j++) {
        var leg = legs[j];
        if (leg.BuyOrSell === 'Sell' && leg.OpenOrClose === 'Close') {
          var sym = (leg.Symbol || '').split(' ')[0].toUpperCase();
          var dir = (leg.Symbol || '').indexOf('C') > 0 ? 'CALLS' : 'PUTS';
          var exitPrice = parseFloat(leg.ExecPrice || leg.FilledPrice || ord.FilledPrice || 0);

          // Find matching open signal
          var sig = findFilledByTicker(sym, dir);
          if (sig && !sig.closed) {
            logClose(sig.id, {
              exitPrice: exitPrice,
              exitReason: 'AUTO_RECONCILE',
            });
            closedCount++;
          }
        }
      }
    }

    return { reconciled: closedCount, totalOrders: orders.length };
  } catch (e) {
    console.error('[SIGNAL-TRACKER] Reconcile error:', e.message);
    return { error: e.message };
  }
}

// -----------------------------------------------------------------
// STATS — the money metric
// -----------------------------------------------------------------
function getStats(opts) {
  load();
  opts = opts || {};
  var days = opts.days || 30;
  var source = opts.source || null;
  var grade = opts.grade || null;

  var cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - days);
  var cutoffStr = cutoff.toISOString();

  // Filter
  var filtered = _signals.filter(function (s) {
    if (s.timestamp < cutoffStr) return false;
    if (source && s.source.indexOf(source) === -1) return false;
    if (grade && s.grade !== grade) return false;
    return true;
  });

  var total = filtered.length;
  var filled = filtered.filter(function (s) { return s.filled; });
  var closed = filtered.filter(function (s) { return s.closed; });
  var wins = closed.filter(function (s) { return s.won === true; });
  var losses = closed.filter(function (s) { return s.won === false; });

  var totalPnl = 0;
  var totalPct = 0;
  var bestTrade = null;
  var worstTrade = null;

  for (var i = 0; i < closed.length; i++) {
    var c = closed[i];
    totalPnl += (c.pnlDollar || 0);
    totalPct += (c.pnlPercent || 0);
    if (!bestTrade || (c.pnlPercent || 0) > (bestTrade.pnlPercent || 0)) bestTrade = c;
    if (!worstTrade || (c.pnlPercent || 0) < (worstTrade.pnlPercent || 0)) worstTrade = c;
  }

  var winRate = closed.length > 0 ? (wins.length / closed.length * 100) : 0;
  var avgReturn = closed.length > 0 ? (totalPct / closed.length) : 0;
  var avgHold = 0;
  if (closed.length > 0) {
    var totalHold = 0;
    for (var j = 0; j < closed.length; j++) totalHold += (closed[j].holdTimeMin || 0);
    avgHold = totalHold / closed.length;
  }

  // Stats by grade
  var byGrade = {};
  for (var g = 0; g < closed.length; g++) {
    var gr = closed[g].grade || 'UNGRADED';
    if (!byGrade[gr]) byGrade[gr] = { total: 0, wins: 0, pnl: 0 };
    byGrade[gr].total++;
    if (closed[g].won) byGrade[gr].wins++;
    byGrade[gr].pnl += (closed[g].pnlDollar || 0);
  }
  // Calculate win rates per grade
  var gradeKeys = Object.keys(byGrade);
  for (var h = 0; h < gradeKeys.length; h++) {
    var bg = byGrade[gradeKeys[h]];
    bg.winRate = bg.total > 0 ? (bg.wins / bg.total * 100).toFixed(1) + '%' : '0%';
    bg.avgPnl = bg.total > 0 ? (bg.pnl / bg.total).toFixed(0) : 0;
  }

  // Stats by source
  var bySource = {};
  for (var s = 0; s < closed.length; s++) {
    var src = closed[s].source || 'UNKNOWN';
    if (!bySource[src]) bySource[src] = { total: 0, wins: 0, pnl: 0 };
    bySource[src].total++;
    if (closed[s].won) bySource[src].wins++;
    bySource[src].pnl += (closed[s].pnlDollar || 0);
  }
  var srcKeys = Object.keys(bySource);
  for (var k = 0; k < srcKeys.length; k++) {
    var bs = bySource[srcKeys[k]];
    bs.winRate = bs.total > 0 ? (bs.wins / bs.total * 100).toFixed(1) + '%' : '0%';
  }

  return {
    period: days + ' days',
    totalSignals: total,
    filled: filled.length,
    closed: closed.length,
    pending: total - filled.length,
    open: filled.length - closed.length,
    wins: wins.length,
    losses: losses.length,
    winRate: winRate.toFixed(1) + '%',
    totalPnl: '$' + totalPnl.toFixed(0),
    avgReturn: avgReturn.toFixed(1) + '%',
    avgHoldMin: Math.round(avgHold),
    bestTrade: bestTrade ? { ticker: bestTrade.ticker, pnl: bestTrade.pnlPercent.toFixed(1) + '%' } : null,
    worstTrade: worstTrade ? { ticker: worstTrade.ticker, pnl: worstTrade.pnlPercent.toFixed(1) + '%' } : null,
    byGrade: byGrade,
    bySource: bySource,
  };
}

// -----------------------------------------------------------------
// HELPERS
// -----------------------------------------------------------------
function findSignal(id) {
  for (var i = 0; i < _signals.length; i++) {
    if (_signals[i].id === id) return _signals[i];
  }
  return null;
}

function findPendingByTicker(ticker, direction) {
  ticker = (ticker || '').toUpperCase();
  direction = (direction || '').toUpperCase();
  for (var i = _signals.length - 1; i >= 0; i--) {
    var s = _signals[i];
    if (s.ticker === ticker && s.direction === direction && !s.filled) return s;
  }
  return null;
}

function findFilledByTicker(ticker, direction) {
  ticker = (ticker || '').toUpperCase();
  direction = (direction || '').toUpperCase();
  for (var i = _signals.length - 1; i >= 0; i--) {
    var s = _signals[i];
    if (s.ticker === ticker && s.direction === direction && s.filled && !s.closed) return s;
  }
  return null;
}

function getHistory(opts) {
  load();
  opts = opts || {};
  var limit = opts.limit || 50;
  return _signals.slice(-limit).reverse();
}

module.exports = {
  logSignal: logSignal,
  logFill: logFill,
  logClose: logClose,
  autoReconcile: autoReconcile,
  getStats: getStats,
  getHistory: getHistory,
};
